### PR TITLE
Bugfix/crash on load

### LINKED ISSUE #2: Change minSdkVersion to 4
when deploying my application to phone i get this gradle build error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 23 declared in library [manager:react-native-fingerprint-android:unspecified] /Users/ant/github/pdr-manager/android/app/build/intermediates/exploded-aar/manager/react-native-fingerprint-android/unspecified/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="io.jari.fingerprint" to force usage
```

simple enough, so i went ahead and added `<uses-sdk tools:overrideLibrary="io.jari.fingerprint" />` to my application's `AndroidManifest.xml` which got the build working again. 

something tells me that what i did (above) shouldn't be necessary, however. perhaps the minimum sdk version for this library should be lower?

### PR DESCRIPTION
**Pull request by mlabrum**
https://github.com/jariz/react-native-fingerprint-android/pull/3 is a little scary for me, dropping windows support, changing how the library is used

So I've only focused on fixing https://github.com/jariz/react-native-fingerprint-android/compare/master...mlabrum:bugfix/crash-on-load?expand=1

edit: fixes #2 as well

### CODE REVIEW

**Comment by yinghang** [comment]
PR gonna be done soon? App doesn't run on devices running on older Android versions or devices without fingerprint hardware

**Comment by jariz** [comment]
I somehow totally missed this, so thanks for the ping @yinghang.
Yea, this is exactly what I was looking for, #3 unnecessarily breaks way too much backwards compatibility.
The magic numbers are kind of nasty, but they're better than completely dropping the constants.

**Comment by mlabrum** [comment]
Thanks :D I agree with the magic numbers....  Do you have any ideas for a
work around?

**Comment by jariz** [comment]
I sadly don't, it's really weird they didn't add the constants to FingerprintManagerCompat as well.

**Pull request merged**
